defaults:
  - env/libero_10@env.train
  - env/libero_10@env.eval
  - model/qwen_vla@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_10_grpo_qwenvla"
    logger_backends: ["wandb"]

  max_epochs: 200
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 25

  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  rollout_epoch: 4
  eval_rollout_epoch: 1
  group_size: 8
  reward_type: action_level
  logprob_type: token_level
  entropy_type: token_level
  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0
  gamma: 0.99
  gae_lambda: 0.95
  reward_coef: 5.0

  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 1.0
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

  filter_rewards: True
  rewards_lower_bound: 0.5
  rewards_upper_bound: 4.5

env:
  group_name: "EnvGroup"
  enable_offload: False
  train:
    total_num_envs: 128
    group_size: 8
    max_steps_per_rollout_epoch: 512
    max_episode_steps: 512
    reset_gripper_open: False
  eval:
    total_num_envs: 500
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 512
    max_steps_per_rollout_epoch: 512
    group_size: 1
    use_fixed_reset_state_ids: True
    use_ordered_reset_state_ids: True
    reset_gripper_open: False
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 1
  model:
    model_path: "/path/to/Qwen2.5-VL-0.5B"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 32
  global_batch_size: 16384
  seed: 1234
  enable_offload: True
  model:
    model_path: "/path/to/Qwen2.5-VL-0.5B"
    model_type: "qwen2.5_vla"
    action_dim: 7
    num_action_chunks: 1
    add_value_head: True
    max_prompt_length: 256
    trust_remote_code: True
  optim:
    lr: 2.0e-5
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0
  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False

